### PR TITLE
Improve translations

### PR DESCRIPTION
**Pull request by Kaaveh**

### CODE REVIEW

**Review by sabajamalian — APPROVED** [review]

**Comment by rbabayan** [comment]
Thanks for all the improvements! So far so good. Let us know when all changes over so we can do the final review and merge 🎉

**Comment by Kaaveh** [comment]
> 
> 
> Thanks for all the improvements! So far so good. Let us know when all changes over so we can do the final review and merge 🎉

Sure, I'll notice you.

**Comment by Kaaveh** [comment]
I've finished reading the book. Now, you can review my commits.

**Review by rbabayan — APPROVED** [review]

**Comment by sabajamalian** [comment]
Thanks @Kaaveh for your help and contributions! The changes will be included in the next version of the book. There is currently no timeline on when the next version will be released, but we will make sure to include a note in the preface, to thank you! :)

**Comment by Kaaveh** [comment]
Your welcome! ;)

**Pull request merged**
